"""
Bylaws Generator - Automated cooperative bylaws generation.

Creates legally-compliant bylaws based on user choices about governance,
profit distribution, and membership structure.
"""

from dataclasses import dataclass, field
from typing import Dict, List, Optional, Any
from enum import Enum
from datetime import datetime


class EntityType(Enum):
    """Type of cooperative entity."""
    REIC = "Real Estate Investment Cooperative"
    LLC_COOP = "Cooperative LLC"
    LCA = "Limited Cooperative Association"
    NONPROFIT = "Nonprofit Cooperative"


class VotingStructure(Enum):
    """How voting power is allocated."""
    ONE_MEMBER_ONE_VOTE = "one_member_one_vote"
    PATRONAGE_BASED = "patronage_based"
    QUADRATIC = "quadratic"
    HYBRID = "hybrid"


class SurplusDistribution(Enum):
    """How surplus/profit is distributed."""
    EQUAL = "equal_shares"
    PATRONAGE = "patronage_dividends"
    CAPITAL_CONTRIBUTION = "capital_based"
    HYBRID = "hybrid"


class BoardElection(Enum):
    """How board members are elected."""
    AT_LARGE = "at_large"
    BY_DISTRICT = "by_district"
    BY_CLASS = "by_member_class"
    ROTATING = "rotating"


@dataclass
class MemberClass:
    """A class of membership."""
    name: str
    description: str
    voting_rights: bool = True
    equity_rights: bool = True
    board_seats: int = 0
    minimum_investment: float = 0


@dataclass
class BylawsConfig:
    """Configuration for bylaws generation."""
    cooperative_name: str
    entity_type: EntityType
    state: str
    purpose: str
    
    # Governance
    voting_structure: VotingStructure = VotingStructure.ONE_MEMBER_ONE_VOTE
    board_size: int = 5
    board_term_years: int = 2
    board_election: BoardElection = BoardElection.AT_LARGE
    quorum_percentage: float = 0.25
    
    # Membership
    member_classes: List[MemberClass] = field(default_factory=list)
    minimum_investment: float = 1000
    maximum_investment: float = 100000
    
    # Surplus distribution
    surplus_distribution: SurplusDistribution = SurplusDistribution.PATRONAGE
    reserve_percentage: float = 0.20
    
    # Anti-speculation
    appreciation_cap: Optional[float] = 0.03  # 3% annual
    transfer_restrictions: bool = True
    right_of_first_refusal: bool = True


@dataclass
class GeneratedBylaws:
    """Generated bylaws document."""
    config: BylawsConfig
    generated_at: datetime = field(default_factory=datetime.now)
    sections: Dict[str, str] = field(default_factory=dict)
    
    def to_markdown(self) -> str:
        """Generate markdown version of bylaws."""
        lines = [
            f"# BYLAWS OF {self.config.cooperative_name.upper()}",
            f"*A {self.config.entity_type.value}*",
            "",
            f"**Organized under the laws of the State of {self.config.state}**",
            "",
            f"*Adopted: {self.generated_at.strftime('%B %d, %Y')}*",
            "",
            "---",
            "",
        ]
        
        for title, content in self.sections.items():
            lines.append(f"## {title}")
            lines.append("")
            lines.append(content)
            lines.append("")
        
        return "\n".join(lines)


class BylawsGenerator:
    """Generator for cooperative bylaws."""
    
    def __init__(self):
        self.templates: Dict[str, str] = self._load_templates()
    
    def _load_templates(self) -> Dict[str, str]:
        """Load clause templates."""
        return {
            'purpose': """
### Section 1.1 - Purpose
The purpose of this Cooperative is to {purpose}. The Cooperative shall operate 
on a cooperative basis for the mutual benefit of its Members, who shall be the 
primary users and beneficiaries of the Cooperative's services.
""",
            'membership': """
### Section 2.1 - Eligibility
Any natural person who supports the purposes of the Cooperative may apply for 
membership. Membership is open without discrimination.

### Section 2.2 - Member Investment
{member_investment}

### Section 2.3 - Member Rights
Each Member in good standing shall have the right to:
- Vote in Member meetings
- Receive patronage dividends as declared
- Inspect Cooperative records
- Participate in Member education programs
""",
            'voting': """
### Section 3.1 - Voting Rights
{voting_rights}

### Section 3.2 - Quorum
A quorum for any Member meeting shall consist of {quorum}% of the total 
membership, present in person or by proxy.

### Section 3.3 - Decisions
Except as otherwise provided, decisions shall be made by a majority vote of 
Members present and voting.
""",
            'board': """
### Section 4.1 - Board of Directors
The Cooperative shall be governed by a Board of Directors consisting of 
{board_size} directors, each serving a term of {term_years} years.

### Section 4.2 - Election
Directors shall be elected {election_method}.

### Section 4.3 - Powers and Duties
The Board shall have full authority to manage the business and affairs of 
the Cooperative, subject to these Bylaws and applicable law.
""",
            'surplus': """
### Section 5.1 - Annual Surplus
The net surplus of the Cooperative, after deducting operating expenses, 
shall be allocated as follows:

{surplus_allocation}

### Section 5.2 - Patronage Dividends
Patronage dividends shall be distributed to Members based on {patronage_basis}.
""",
            'anti_speculation': """
### Section 6.1 - Transfer Restrictions
{transfer_restrictions}

### Section 6.2 - Appreciation Cap
{appreciation_cap}

### Section 6.3 - Right of First Refusal
{first_refusal}
""",
        }
    
    def generate(self, config: BylawsConfig) -> GeneratedBylaws:
        """Generate bylaws from configuration."""
        sections = {}
        
        # Article I: Purpose
        sections["ARTICLE I - NAME AND PURPOSE"] = self._generate_purpose(config)
        
        # Article II: Membership
        sections["ARTICLE II - MEMBERSHIP"] = self._generate_membership(config)
        
        # Article III: Voting
        sections["ARTICLE III - MEETINGS AND VOTING"] = self._generate_voting(config)
        
        # Article IV: Board
        sections["ARTICLE IV - BOARD OF DIRECTORS"] = self._generate_board(config)
        
        # Article V: Surplus Distribution
        sections["ARTICLE V - SURPLUS DISTRIBUTION"] = self._generate_surplus(config)
        
        # Article VI: Anti-Speculation (if applicable)
        if config.appreciation_cap or config.transfer_restrictions:
            sections["ARTICLE VI - COMMUNITY PRESERVATION"] = self._generate_anti_speculation(config)
        
        return GeneratedBylaws(config=config, sections=sections)
    
    def _generate_purpose(self, config: BylawsConfig) -> str:
        return f"""
### Section 1.1 - Name
The name of this organization shall be **{config.cooperative_name}**.

### Section 1.2 - Purpose
{config.purpose}

### Section 1.3 - Cooperative Principles
This Cooperative shall operate in accordance with internationally recognized 
cooperative principles, including democratic member control, member economic 
participation, and concern for community.
"""
    
    def _generate_membership(self, config: BylawsConfig) -> str:
        investment_text = f"""
The minimum investment required for membership shall be **${config.minimum_investment:,.0f}**.
The maximum investment per member shall not exceed **${config.maximum_investment:,.0f}**."""
        
        if config.member_classes:
            class_text = "\n\n### Section 2.4 - Member Classes\n"
            for mc in config.member_classes:
                class_text += f"- **{mc.name}**: {mc.description}\n"
            investment_text += class_text
        
        return self.templates['membership'].format(member_investment=investment_text)
    
    def _generate_voting(self, config: BylawsConfig) -> str:
        voting_map = {
            VotingStructure.ONE_MEMBER_ONE_VOTE: "Each Member shall have one (1) vote on all matters.",
            VotingStructure.PATRONAGE_BASED: "Voting power shall be allocated based on patronage.",
            VotingStructure.QUADRATIC: "Voting shall utilize quadratic voting mechanics.",
            VotingStructure.HYBRID: "Voting power combines one-member-one-vote with quadratic voting.",
        }
        
        return self.templates['voting'].format(
            voting_rights=voting_map.get(config.voting_structure, "One member, one vote."),
            quorum=int(config.quorum_percentage * 100)
        )
    
    def _generate_board(self, config: BylawsConfig) -> str:
        election_map = {
            BoardElection.AT_LARGE: "at-large by the full membership",
            BoardElection.BY_DISTRICT: "by geographic district",
            BoardElection.BY_CLASS: "by member class",
            BoardElection.ROTATING: "on a rotating basis with staggered terms",
        }
        
        return self.templates['board'].format(
            board_size=config.board_size,
            term_years=config.board_term_years,
            election_method=election_map.get(config.board_election, "at-large")
        )
    
    def _generate_surplus(self, config: BylawsConfig) -> str:
        reserve_pct = int(config.reserve_percentage * 100)
        remaining = 100 - reserve_pct
        
        allocation = f"""
1. **{reserve_pct}%** to Cooperative reserves
2. **{remaining}%** distributed as patronage dividends to Members"""
        
        patronage_map = {
            SurplusDistribution.EQUAL: "equal shares among all Members",
            SurplusDistribution.PATRONAGE: "their proportional use of Cooperative services",
            SurplusDistribution.CAPITAL_CONTRIBUTION: "their capital contribution",
            SurplusDistribution.HYBRID: "a combination of participation and capital contribution",
        }
        
        return self.templates['surplus'].format(
            surplus_allocation=allocation,
            patronage_basis=patronage_map.get(config.surplus_distribution, "patronage")
        )
    
    def _generate_anti_speculation(self, config: BylawsConfig) -> str:
        transfer = "Member shares may not be transferred without Board approval." if config.transfer_restrictions else "Member shares are freely transferable."
        
        cap = ""
        if config.appreciation_cap:
            cap = f"Any increase in the value of Member shares shall be capped at **{config.appreciation_cap*100:.0f}% per year**, compounded annually."
        else:
            cap = "There is no cap on share appreciation."
        
        refusal = "The Cooperative shall have the right of first refusal on any proposed transfer of shares." if config.right_of_first_refusal else ""
        
        return self.templates['anti_speculation'].format(
            transfer_restrictions=transfer,
            appreciation_cap=cap,
            first_refusal=refusal
        )


def get_bylaws_generator() -> BylawsGenerator:
    """Factory function for bylaws generator."""
    return BylawsGenerator()
